/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package s3_t2_niv3_ex1_montseliz;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
